-- AlterTable
ALTER TABLE "Doctor" ALTER COLUMN "fullName" DROP NOT NULL,
ALTER COLUMN "specialization" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Patient" ALTER COLUMN "fullName" DROP NOT NULL,
ALTER COLUMN "dob" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Staff" ALTER COLUMN "fullName" DROP NOT NULL,
ALTER COLUMN "position" DROP NOT NULL;
